name: Docker Image RC-CI

on:
  pull_request:
    branches: [ "develop" ]
    paths-ignore: 
      - '**.md'

jobs:

  build:
    uses: mlx-dev/strapi-v4-docker/.github/workflows/WC-Docker-Image-Build-Push.yml@main
