name: Docker Image main PR

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - '**.md'
      - '**/.github/workflows/**'

jobs:

  build:
    uses: ${{ github.repository }}/.github/workflows/WC-Docker-Image-Build-Push.yml@main
    with:
      pushBuild: false
      isRcBuild: false
      dockerFile: './Dockerfile.Production'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
