name: Docker Image develop PR

on:
  pull_request:
    branches: [ "develop" ]
    paths-ignore: 
      - '**.md'
      - '**/.github/workflows/**'

jobs:

  build:
    uses: ${{ github.repository }}/.github/workflows/WC-Docker-Image-Build-Push.yml@develop
    with:
      pushBuild: false
      isRcBuild: true
      dockerFile: './Dockerfile.Production'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
