name: Docker Image develop PR

on:
  pull_request:
    branches: [ "develop" ]
    paths-ignore: 
      - '**.md'
      - '**/.github/workflows/**'

jobs:

  build:
    uses: mlx-dev/strapi-v4-docker/.github/workflows/WC-Docker-Image-Build-Push.yml@main
    with:
      pushBuild: false
      isRcBuild: true
      dockerFile: './Dockerfile.Develop'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
