name: Docker Image main PR

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - '**.md'
      - '**/.github/workflows/**'

jobs:

  build:
    uses: mlx-dev/strapi-v4-docker/.github/workflows/WC-Docker-Image-Build-Push.yml@main
    with:
      pushBuild: false
      isRcBuild: false
      dockerFile: './Dockerfile.Prod'
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
